version: '3'
services:
  web:
    image: php:7.2.2-apache
    container_name: pricesearcher_php_web
    depends_on:
      - db
    volumes:
      - ./api:/usr/local/etc/php/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true

  db:
    image: mysql
    container_name: pricesearcherdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pricesearcher
      MYSQL_USER: user
      MYSQL_PASSWORD: test321
    ports:
    - "3306:3306"